// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv4UdYDvCzWpLciMxYR4XHRsAM1kP70Cg',
    appId: '1:326523884626:web:1da52f38c4437d728bfb8b',
    messagingSenderId: '326523884626',
    projectId: 'e-learning-smk-pi-77d23',
    authDomain: 'e-learning-smk-pi-77d23.firebaseapp.com',
    storageBucket: 'e-learning-smk-pi-77d23.appspot.com',
    measurementId: 'G-1NW0H8GHNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJDQXTFauc5nJsX5j_zYaTe1m4ylrURuk',
    appId: '1:326523884626:android:cd81a1064273e7c68bfb8b',
    messagingSenderId: '326523884626',
    projectId: 'e-learning-smk-pi-77d23',
    storageBucket: 'e-learning-smk-pi-77d23.appspot.com',
  );
}
